import Head from "next/head";
import {BsFillMoonStarsFill} from "react-icons/bs"
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from "react-icons/ai"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <main className="bg-gradient-to-r from-black to-purple-950 px-10 ">
      <section className="min-h-screen">
       <nav className="py-10 mb-12 flex justify-between">
        <h1 className="text-xl font-burtons">Broseph.dev</h1>
        <ul className="flex items-center">
          <li>
            <BsFillMoonStarsFill className="cursor-pointer text-xl"/>
          </li>
          <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 px-4 text-white py-2 rounded-md ml-8"href="#">Resume</a></li>
        </ul>

       </nav>
       <div className="text-center p-10">
        <h2 className=" text-5xl py-2 text-teal-600 font-medium">Jordan Brose</h2>
        <h3 className="text-white">Front End  Developer</h3>
        <p>Based in Australia</p>
       </div>
       <div>
        <a className="text-blue-500 flex"href="#"><AiFillTwitterCircle/></a>
        <a className="text-blue-500 flex"href="#"><AiFillLinkedin/></a>
        <a className="text-blue-500 flex"href="#"><AiFillYoutube/></a>
       </div>
      </section>
    </main>
    </div>
  );
}
